originalPowerCons <- read.csv("household_power_consumption.txt", header = TRUE, sep=";", na.strings="?", nrows=2075259)
originalPowerCons$Date <- as.Date(originalPowerCons$Date, format= "%d/%m/%Y")
powerConsFiltered <- subset(originalPowerCons, Date >= "2007-02-01" & Date <= "2007-02-02")
powerConsFiltered$DateTime <- as.POSIXct(paste(powerConsFiltered$Date, powerConsFiltered$Time))
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
with(powerConsFiltered, plot(Global_active_power~DateTime, type="l", ylab="Global Active Power", xlab=""))
with(powerConsFiltered, plot(Voltage~DateTime, type="l", ylab="Voltage", xlab="datetime", col="black"))
with(powerConsFiltered, plot(Sub_metering_1~DateTime, type="l", ylab="Energy sub metering", xlab="", col="black"))
with(powerConsFiltered, lines(Sub_metering_2~DateTime, col="red"))
with(powerConsFiltered, lines(Sub_metering_3~DateTime, col="blue"))
legend("topright", col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=1.5, bty="n", cex=0.8)
with(powerConsFiltered, plot(Global_reactive_power~DateTime, type="l", ylab="Global_reactive_power", xlab="datetime", col="black"))
dev.off()
